<?php

namespace Bookshelf\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LibraryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LibraryRepository extends EntityRepository
{
}
